### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by FengFengmomo** [w3reality/es-pack-js#6]
install es-pack-js error
nodejs v16.16.0
windows 10

use npm i
PS C:\Users\ZLD> npm i es-pack-js@0.5.13 -g
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm notice
npm notice New major version of npm available! 8.11.0 -> 10.1.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.1.0
npm notice Run npm install -g npm@10.1.0 to update!
npm notice
npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path G:\nodejs\node_global\node_modules\es-pack-js\node_modules\puppeteer
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     G:\nodejs\node_cache\_logs\2023-09-27T15_25_40_795Z-debug-0.log

use cnpm i (cnpm is a China version npm):
PS C:\Users\ZLD> cnpm i es-pack-js@0.5.13 -g
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Downloading es-pack-js to G:\nodejs\node_global\node_modules\es-pack-js_tmp
Copying G:\nodejs\node_global\node_modules\es-pack-js_tmp\.store\es-pack-js@0.5.13\node_modules\es-pack-js to G:\nodejs\node_global\node_modules\es-pack-js
Installing es-pack-js's dependencies to G:\nodejs\node_global\node_modules\es-pack-js/node_modules
[1/22] base64-arraybuffer@^0.2.0 installed at node_modules\.store\base64-arraybuffer@0.2.0\node_modules\base64-arraybuffer
[2/22] babel-plugin-add-module-exports@^1.0.4 installed at node_modules\.store\babel-plugin-add-module-exports@1.0.4\node_modules\babel-plugin-add-module-exports
[3/22] toml@^3.0.0 installed at node_modules\.store\toml@3.0.0\node_modules\toml
[4/22] fs-extra@^9.0.1 installed at node_modules\.store\fs-extra@9.1.0\node_modules\fs-extra
[5/22] webpack-bundle-analyzer@^4.5.0 installed at node_modules\.store\webpack-bundle-analyzer@4.9.1\node_modules\webpack-bundle-analyzer
[6/22] yargs@^16.1.0 installed at node_modules\.store\yargs@16.2.0\node_modules\yargs
[7/22] express@^4.17.1 installed at node_modules\.store\express@4.18.2\node_modules\express
[8/22] @babel/core@^7.12.3 installed at node_modules\.store\@babel+core@7.23.0\node_modules\@babel\core
[9/22] @babel/standalone@^7.12.6 installed at node_modules\.store\@babel+standalone@7.23.1\node_modules\@babel\standalone
[10/22] @babel/eslint-parser@^7.17.0 installed at node_modules\.store\@babel+eslint-parser@7.22.15\node_modules\@babel\eslint-parser
[11/22] eslint@^7.12.1 installed at node_modules\.store\eslint@7.32.0\node_modules\eslint
[12/22] terser-webpack-plugin@^5.3.4 installed at node_modules\.store\terser-webpack-plugin@5.3.9\node_modules\terser-webpack-plugin
[13/22] babel-loader@^8.1.0 installed at node_modules\.store\babel-loader@8.3.0\node_modules\babel-loader
[14/22] eslint-webpack-plugin@^3.1.1 installed at node_modules\.store\eslint-webpack-plugin@3.2.0\node_modules\eslint-webpack-plugin
[15/22] webpack-cli@^4.9.2 installed at node_modules\.store\webpack-cli@4.10.0\node_modules\webpack-cli
[16/22] webpack@^5.70.0 installed at node_modules\.store\webpack@5.88.2\node_modules\webpack
[17/22] typescript@^4.7.4 installed at node_modules\.store\typescript@4.9.5\node_modules\typescript
[18/22] ts-loader@^9.3.1 installed at node_modules\.store\ts-loader@9.4.4\node_modules\ts-loader
[19/22] @babel/preset-env@^7.12.1 installed at node_modules\.store\@babel+preset-env@7.22.20\node_modules\@babel\preset-env
[20/22] jest@^27.2.0 installed at node_modules\.store\jest@27.5.1\node_modules\jest
[21/22] jest-puppeteer@^6.1.0 installed at node_modules\.store\jest-puppeteer@6.2.0\node_modules\jest-puppeteer
[22/22] puppeteer@^13.1.2 installed at node_modules\.store\puppeteer@13.7.0\node_modules\puppeteer
[npminstall:runscript:error] es-pack-js@0.5.13 run postinstall (cd ./node-polyfill && npm run install) && (cd ./rustwasm-wrapper && npm i) error: Error: Command failed with exit code 1: (cd ./node-polyfill && npm run install) && (cd ./rustwasm-wrapper && npm i)
    at makeError (G:\nodejs\node_global\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (G:\nodejs\node_global\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.runScript (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\utils.js:261:12)
    at async runLifecycleScripts (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:66:7)
    at async _install (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:168:5)
    at async module.exports (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:87:5)
    at async module.exports (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\global_install.js:71:5)
    at async G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js:406:5 {
  shortMessage: 'Command failed with exit code 1: (cd ./node-polyfill && npm run install) && (cd ./rustwasm-wrapper && npm i)',
  command: '(cd ./node-polyfill && npm run install) && (cd ./rustwasm-wrapper && npm i)',
  escapedCommand: '"(cd" "./node-polyfill" "&&" npm run "install)" "&&" "(cd" "./rustwasm-wrapper" "&&" npm "i)"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Install fail! Error: run postinstall error, please remove node_modules before retry!
Command failed with exit code 1: (cd ./node-polyfill && npm run install) && (cd ./rustwasm-wrapper && npm i)
Error: Command failed with exit code 1: (cd ./node-polyfill && npm run install) && (cd ./rustwasm-wrapper && npm i)
    at makeError (G:\nodejs\node_global\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (G:\nodejs\node_global\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.runScript (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\utils.js:261:12)
    at async runLifecycleScripts (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:66:7)
    at async _install (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:168:5)
    at async module.exports (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:87:5)
    at async module.exports (G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\global_install.js:71:5)
    at async G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js:406:5
npminstall version: 7.11.1
npminstall argv: G:\nodejs\node.exe G:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\ZLD\.cnpmrc --disturl=https://cdn.npmmirror.com/binaries/node --registry=https://registry.npmmirror.com es-pack-js@0.5.13 -g

How can i fix this error? which nodejs version should i use?

**Comment by j-devel** [comment]
For installing on Windows, maybe, this instruction is useful - https://github.com/w3reality/three-geo#building-on-windows

**Comment by FengFengmomo** [comment]
> For installing on Windows, maybe, this instruction is useful - https://github.com/w3reality/three-geo#building-on-windows

I install it success!
env:
windows10
nodejs: 14.17.0 

execute steps:
1、install nodejs14.17.0
2、npm install --ignore-scripts
3、npm config set script-shell
4、npm run build
5、fix error and install needed module
6、npm run build
7、success！

**Comment by j-devel** [comment]
Glad to hear that it worked!
